package com.sds.hakli.dao;

import java.util.ArrayList;
import java.util.List;

import org.hibernate.HibernateException;
import org.hibernate.Session;

import com.sds.hakli.domain.BranchTop;
import com.sds.hakli.domain.Tp2kb;
import com.sds.hakli.domain.Vp2kb;
import com.sds.hakli.domain.Vrecp2kb;
import com.sds.hakli.domain.Vreportproduktivitas;
import com.sds.utils.db.StoreHibernateUtil;

public class Tp2kbDAO {

	private Session session;

	@SuppressWarnings("unchecked")
	public List<Tp2kb> listPaging(int first, int second, String filter, String orderby) throws Exception {
		List<Tp2kb> oList = null;
		if (filter == null || "".equals(filter))
			filter = "0 = 0";
		session = StoreHibernateUtil.openSession();
		oList = session.createSQLQuery("select * from tp2kb  " + "where " + filter + " order by " + orderby + " limit "
				+ second + " offset " + first).addEntity(Tp2kb.class).list();

		session.close();
		return oList;
	}

	public int pageCount(String filter) throws Exception {
		int count = 0;
		if (filter == null || "".equals(filter))
			filter = "0 = 0";
		session = StoreHibernateUtil.openSession();
		count = Integer.parseInt((String) session.createSQLQuery("select count(*) from Tp2kb " + "where " + filter)
				.uniqueResult().toString());
		session.close();
		return count;
	}

	@SuppressWarnings("unchecked")
	public List<Tp2kb> listByFilter(String filter, String orderby) throws Exception {
		List<Tp2kb> oList = null;
		if (filter == null || "".equals(filter))
			filter = "0 = 0";
		session = StoreHibernateUtil.openSession();
		oList = session.createQuery("from Tp2kb where " + filter + " order by " + orderby).list();
		session.close();
		return oList;
	}

	public Tp2kb findByPk(Integer pk) throws Exception {
		session = StoreHibernateUtil.openSession();
		Tp2kb oForm = (Tp2kb) session.createQuery("from Tp2kb where tp2kbpk = " + pk).uniqueResult();
		session.close();
		return oForm;
	}

	@SuppressWarnings("rawtypes")
	public List listStr(String fieldname) throws Exception {
		List oList = new ArrayList();
		session = StoreHibernateUtil.openSession();
		oList = session.createQuery("select " + fieldname + " from Tp2kb order by " + fieldname).list();
		session.close();
		return oList;
	}

	public Tp2kb findByFilter(String filter) throws Exception {
		session = StoreHibernateUtil.openSession();
		Tp2kb oForm = (Tp2kb) session.createQuery("from Tp2kb where " + filter).uniqueResult();
		session.close();
		return oForm;
	}

	@SuppressWarnings("unchecked")
	public List<Vp2kb> listVerifikasiTim(String filter, String orderby) throws Exception {
		List<Vp2kb> oList = null;
		if (filter == null || "".equals(filter))
			filter = "0 = 0";
		session = StoreHibernateUtil.openSession();
		oList = session
				.createSQLQuery("SELECT TP2KBBOOKPK, TANGGOTAPK, NOANGGOTA, NAMA, ALAMAT, CABANG, TP2KBBOOK.NOSTR, TGLMULAI, TGLAKHIR, SUM(TOTALKEGIATANWV) AS TOTALKEGIATANWV "
						+ "FROM TP2KBBOOK JOIN TP2KB ON TP2KBBOOKPK = TP2KBBOOKFK JOIN TANGGOTA ON TP2KB.TANGGOTAFK = TANGGOTAPK JOIN MCABANG ON MCABANGFK = MCABANGPK "
						+ "JOIN MP2KBKEGIATAN ON MP2KBKEGIATANFK = MP2KBKEGIATANPK WHERE " + filter
						+ " GROUP BY TP2KBBOOKPK, TANGGOTAPK, NOANGGOTA, NAMA, ALAMAT, CABANG, TP2KBBOOK.NOSTR, TGLMULAI, TGLAKHIR HAVING SUM(TOTALKEGIATANWV) > 0 ORDER BY " + orderby)
				.addEntity(Vp2kb.class).list();

		session.close();
		return oList;
	}
	
	@SuppressWarnings("unchecked")
	public List<Vp2kb> listVerifikasiKomisi(String filter, String orderby) throws Exception {
		List<Vp2kb> oList = null;
		if (filter == null || "".equals(filter))
			filter = "0 = 0";
		session = StoreHibernateUtil.openSession();
		oList = session
				.createSQLQuery("SELECT CABANG, TANGGOTAPK, NOANGGOTA, NAMA, ALAMAT, SUM(TOTALKEGIATANWV) AS TOTALKEGIATANWV, SUM(TOTALTIMAPPROVE) AS TOTALTIMAPPROVE "
						+ "FROM TP2KB JOIN TANGGOTA ON TANGGOTAFK = TANGGOTAPK JOIN MCABANG ON MCABANGFK = MCABANGPK "
						+ "JOIN MP2KBKEGIATAN ON MP2KBKEGIATANFK = MP2KBKEGIATANPK WHERE " + filter
						+ " GROUP BY CABANG, TANGGOTAPK, NOANGGOTA, NAMA, ALAMAT HAVING SUM(TOTALTIMAPPROVE) > 0 ORDER BY " + orderby)
				.addEntity(Vp2kb.class).list();

		session.close();
		return oList;
	}
	
	@SuppressWarnings("unchecked")
	public List<Vrecp2kb> listRecLetter(String filter, String orderby) throws Exception {
		List<Vrecp2kb> oList = null;
		if (filter == null || "".equals(filter))
			filter = "0 = 0";
		session = StoreHibernateUtil.openSession();
		oList = session
				.createSQLQuery("SELECT TANGGOTAPK, TP2KBBOOK.NOSTR AS NOSTR, NOANGGOTA, NAMA, CABANG, SUM(TOTALSKP) AS TOTALSKP FROM TP2KB JOIN TANGGOTA ON TANGGOTAFK = TANGGOTAPK "
						+ "JOIN MCABANG ON MCABANGFK = MCABANGPK JOIN TP2KBBOOK ON TP2KBBOOKFK = TP2KBBOOKPK WHERE " + filter + " GROUP BY TANGGOTAPK, TP2KBBOOK.NOSTR, NOANGGOTA, NOANGGOTA, NAMA, CABANG HAVING SUM(TOTALSKP) > 5 ORDER BY " + orderby)
				.addEntity(Vrecp2kb.class).list();

		session.close();
		return oList;
	}

	public void save(Session session, Tp2kb oForm) throws HibernateException, Exception {
		session.saveOrUpdate(oForm);
	}

	public void delete(Session session, Tp2kb oForm) throws HibernateException, Exception {
		session.delete(oForm);
	}

	public int getSumWaitTimP2KB(String filter) throws Exception {
		int count = 0;
		if (filter == null || "".equals(filter))
			filter = "0 = 0";
		session = StoreHibernateUtil.openSession();
		count = Integer.parseInt((String) session.createSQLQuery("select coalesce(sum(totalkegiatanwv),0) from Tp2kb join Tanggota on tanggotafk = tanggotapk join Mcabang on mcabangfk = mcabangpk where " + filter)
				.uniqueResult().toString());
		session.close();
		return count;
	}
	
	public int getSumWaitKomisiP2KB(String filter) throws Exception {
		int count = 0;
		if (filter == null || "".equals(filter))
			filter = "0 = 0";
		session = StoreHibernateUtil.openSession();
//		count = Integer.parseInt((String) session.createSQLQuery("select coalesce(sum(totaltimapprove),0) from Tp2kb join Tanggota on tanggotafk = tanggotapk join Mcabang on mcabangfk = mcabangpk where " + filter)
//				.uniqueResult().toString());
		count = Integer.parseInt((String) session.createSQLQuery("select count(*) from Tp2kbbook join Tanggota on tanggotafk = tanggotapk join Mcabang on mcabangfk = mcabangpk where status = 'R' and ispaid = 'Y' and " + filter)
				.uniqueResult().toString());
		session.close();
		return count;
	}
	
	@SuppressWarnings("unchecked")
	public List<BranchTop> listSumWaitTimP2KB(String filter) throws Exception {
		List<BranchTop> oList = null;
		if (filter == null || "".equals(filter))
			filter = "0 = 0";
		session = StoreHibernateUtil.openSession();
		oList = session.createSQLQuery("SELECT MPROVPK AS ID, MPROV.PROVNAME AS NAME, SUM(TOTALKEGIATANWV) AS TOTAL FROM TP2KB " + 
				"JOIN TANGGOTA ON TANGGOTAFK = TANGGOTAPK JOIN MCABANG ON MCABANGFK = MCABANGPK JOIN MPROV ON MPROVFK = MPROVPK " +
				"WHERE TOTALKEGIATANWV > 0 GROUP BY MPROVPK, MPROV.PROVNAME ORDER BY SUM(TOTALKEGIATANWV) DESC").addEntity(BranchTop.class)
				.list();
		session.close();
		return oList;
	}
	
	@SuppressWarnings("unchecked")
	public List<BranchTop> listSumWaitTimP2KBKab(String filter) throws Exception {
		List<BranchTop> oList = null;
		if (filter == null || "".equals(filter))
			filter = "0 = 0";
		session = StoreHibernateUtil.openSession();
		oList = session.createSQLQuery("SELECT MCABANGPK AS ID, CABANG AS NAME, SUM(TOTALKEGIATANWV) AS TOTAL FROM TP2KB " + 
				"JOIN TANGGOTA ON TANGGOTAFK = TANGGOTAPK JOIN MCABANG ON MCABANGFK = MCABANGPK " +
				"WHERE TOTALKEGIATANWV > 0 AND " + filter + " " + 
				"GROUP BY MCABANGPK, CABANG ORDER BY SUM(TOTALKEGIATANWV) DESC").addEntity(BranchTop.class)
				.list();
		session.close();
		return oList;
	}
	
	@SuppressWarnings("unchecked")
	public List<Vreportproduktivitas> reportProduktivitasPaging(int first, int second, String filter, String orderby) throws Exception {
		List<Vreportproduktivitas> oList = null;
		if (filter == null || "".equals(filter))
			filter = "0 = 0";
		session = StoreHibernateUtil.openSession();
		oList = session.createSQLQuery("SELECT SUM(TOTAL) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM ("
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBA01 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBA02 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBA03 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBA04 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBA05 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBA06 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB01 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB01 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB02 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB03 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB04 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB05 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB06 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB07 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB08 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB09 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB10 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB11 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB12 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB13 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB14 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB15 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB16 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB17 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB18 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB19 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB20 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBC01 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBC02 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBD01 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBD02 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE01 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE01 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE02 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE03 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE04 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE05 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE06 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE07 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE08 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE09 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE10 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE11 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG) AS A GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG ORDER BY " + orderby + " LIMIT "
				+ second + " OFFSET " + first).addEntity(Vreportproduktivitas.class).list();

		session.close();
		return oList;
	}
	
	public int reportProduktivitasPageCount(String filter) throws Exception {
		int count = 0;
		if (filter == null || "".equals(filter))
			filter = "0 = 0";
		session = StoreHibernateUtil.openSession();
		count = Integer.parseInt((String) session.createSQLQuery("select count(*) from ("
				+ "SELECT SUM(TOTAL) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM ("
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBA01 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBA02 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBA03 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBA04 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBA05 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBA06 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB01 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB01 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB02 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB03 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB04 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB05 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB06 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB07 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB08 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB09 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB10 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB11 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB12 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB13 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB14 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB15 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB16 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB17 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB18 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB19 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB20 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBC01 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBC02 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBD01 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBD02 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE01 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE01 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE02 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE03 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE04 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE05 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE06 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE07 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE08 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE09 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE10 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
				+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE11 "
				+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
				+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG) AS A GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG) AS A")
				.uniqueResult().toString());
		session.close();
		return count;
	}
	
	@SuppressWarnings("unchecked")
	public List<Vreportproduktivitas> reportProduktivitas(String filter, String orderby) throws Exception {
		List<Vreportproduktivitas> oList = null;
		if (filter == null || "".equals(filter))
			filter = "0 = 0";
		session = StoreHibernateUtil.openSession();
		oList = session
				.createSQLQuery("SELECT SUM(TOTAL) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM ("
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBA01 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBA02 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBA03 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBA04 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBA05 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBA06 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB01 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB01 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB02 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB03 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB04 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB05 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB06 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB07 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB08 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB09 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB10 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB11 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB12 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB13 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB14 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB15 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB16 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB17 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB18 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB19 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBB20 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBC01 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBC02 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBD01 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBD02 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE01 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE01 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE02 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE03 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE04 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE05 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE06 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE07 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE08 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE09 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE10 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG UNION "
						+ "SELECT COUNT(*) AS TOTAL, CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG FROM TP2KBE11 "
						+ "JOIN TANGGOTA ON CHECKEDBYID = NOANGGOTA JOIN MUSERGROUP ON MUSERGROUPFK = MUSERGROUPPK JOIN MCABANG ON MCABANGFK = MCABANGPK WHERE " + filter
						+ "GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG) AS A GROUP BY CHECKEDBYID, CHECKEDBY, USERGROUPNAME, CABANG ORDER BY " + orderby
						)
				.addEntity(Vreportproduktivitas.class).list();

		session.close();
		return oList;
	}
}
